# CircleCI Firebase Deployment Config
version: 2
jobs:
  resolve-dependencies:
    docker:
      - image: cimg/node:14.19.0
    steps:
      - checkout:
      - restore_cache:
          keys:
            - v1-npm-deps-{{ checksum "yarn.lock" }}
            - v1-npm-deps-
      - run:
          name: Resolve dependencies
          command: yarn && cd packages/memo && yarn
      - save_cache:
          key: v1-npm-deps-{{ checksum "yarn.lock" }}
          path: ./node_modules
  build:
    docker: 
      - image: cimg/node:14.19.0
    steps:
      - checkout:
      - run:
          name: Resolve dependencies & Build
          command: cd packages/memo && yarn build
  deploy-firebase:
    docker: 
      - image: cimg/node:14.19.0
    steps:
      - checkout:
      - run:
          name:  Deploy
          command:  ../../node_module/.bin/firebase deploy --token "$FIREBASE_TOKEN" --project "$FIREBASE_PROJECT" --only hosting
      # - run:
      #     name: Build
      #     command: yarn build
      # - run:
      #     name: Firebase Deploy
      #     command: ./node_modules/.bin/firebase deploy --token "$FIREBASE_TOKEN" --project "$FIREBASE_PROJECT"
workflows:
  version: 2
  build-deploy:
    jobs:
      - resolve-dependencies:
          filters:
            branches:
              only:
                - infra/setup-cicd-memo-ui-fe-sangle
      - build:
          filters:
            branches:
              only:
                - infra/setup-cicd-memo-ui-fe-sangle
      - deploy-firebase:
          filters:
            branches:
              only:
                - infra/setup-cicd-memo-ui-fe-sangle
