# CircleCI Firebase Deployment Config
version: 2
jobs:
  build:
    docker:
      - image: cimg/node:14.19.0
    steps:
      - checkout:
      - restore_cache:
          keys:
            - v1-npm-deps-{{ checksum "yarn.lock" }}
            - v1-npm-deps-
      - run:
          name: Resolve dependencies and Build
          command: yarn && cd packages/memo && yarn && yarn build
      - save_cache:
          key: v1-npm-deps-{{ checksum "yarn.lock" }}
          paths:
            - ./node_modules
      - run:
          name: Install Firebase Tools
          command: npm install --prefix=./firebase-deploy firebase-tools 
      - run:
          name:  Firebase Deploy
          command:  cd packages/memo && ../../firebase-deploy/node_modules/.bin/firebase deploy --token "$FIREBASE_TOKEN" --project "$FIREBASE_PROJECT" --only hosting
workflows:
  version: 2
  build-deploy:
    jobs:
      - build:
          filters:
            branches:
              only:
                - infra/setup-cicd-memo-ui-fe-sangle
